title: Rails DateTime Formats
email: andy@goodscary.com
description: > # this means to ignore newlines until "baseurl:"
  I can never remember the formatting for Rails built-in time and date
  formatting. This might help you, but it definitely helps me.
twitter_username: andycroll
github_username:  andycroll

markdown: kramdown
